const ihaleVerileri = [
    {
        "İKN": "2024/1000",
        "Yüklenici Firma": "Hidrolik Pres Döküm Sanayi A.Ş",
        "İhale Adı": "Stop Vana, Sayac Rakoru, Nipel ve Nipel Redüksiyon Temini İşi (2.ve 3.Kısım)",
        "Parti No": 1,
        "Parti Son Teslim Tarihi": "2025-02-14",
        "Parti Tutarı": 7509500,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2024/998877",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Stop Vana, Sayaç Rakoru, Nipel ve Nipel Redüksiyon Temini İşi (1. Kısım)",
        "Parti No": 1,
        "Parti Son Teslim Tarihi": "2025-02-15",
        "Parti Tutarı": 4068750,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2024/123",
        "Yüklenici Firma": "ABC Döküm San. ve Tic. Ltd. Şti.",
        "İhale Adı": "Stop Vana, Sayac Rakoru, Nipel ve Nipel Redüksiyon Temini İşi (4. 5. ve 6.Kısım)",
        "Parti No": 1,
        "Parti Son Teslim Tarihi": "2025-02-18",
        "Parti Tutarı": 1420000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2024/1000",
        "Yüklenici Firma": "Hidrolik Pres Döküm Sanayi A.Ş",
        "İhale Adı": "Stop Vana, Sayac Rakoru, Nipel ve Nipel Redüksiyon Temini İşi (2.ve 3.Kısım)",
        "Parti No": 2,
        "Parti Son Teslim Tarihi": "2025-03-16",
        "Parti Tutarı": 7509500,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2024/998877",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Stop Vana, Sayaç Rakoru, Nipel ve Nipel Redüksiyon Temini İşi (1. Kısım)",
        "Parti No": 2,
        "Parti Son Teslim Tarihi": "2025-03-17",
        "Parti Tutarı": 4068750,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2024/123",
        "Yüklenici Firma": "ABC Döküm San. ve Tic. Ltd. Şti.",
        "İhale Adı": "Stop Vana, Sayac Rakoru, Nipel ve Nipel Redüksiyon Temini İşi (4. 5. ve 6.Kısım)",
        "Parti No": 2,
        "Parti Son Teslim Tarihi": "2025-03-20",
        "Parti Tutarı": 1307500,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2024/1000",
        "Yüklenici Firma": "Hidrolik Pres Döküm Sanayi A.Ş",
        "İhale Adı": "Stop Vana, Sayac Rakoru, Nipel ve Nipel Redüksiyon Temini İşi (2.ve 3.Kısım)",
        "Parti No": 3,
        "Parti Son Teslim Tarihi": "2025-04-15",
        "Parti Tutarı": 7509500,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2024/998877",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Stop Vana, Sayaç Rakoru, Nipel ve Nipel Redüksiyon Temini İşi (1. Kısım)",
        "Parti No": 3,
        "Parti Son Teslim Tarihi": "2025-04-16",
        "Parti Tutarı": 4068750,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2024/123",
        "Yüklenici Firma": "ABC Döküm San. ve Tic. Ltd. Şti.",
        "İhale Adı": "Stop Vana, Sayac Rakoru, Nipel ve Nipel Redüksiyon Temini İşi (4. 5. ve 6.Kısım)",
        "Parti No": 3,
        "Parti Son Teslim Tarihi": "2025-04-19",
        "Parti Tutarı": 2097500,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2024/1000",
        "Yüklenici Firma": "Hidrolik Pres Döküm Sanayi A.Ş",
        "İhale Adı": "Stop Vana, Sayac Rakoru, Nipel ve Nipel Redüksiyon Temini İşi (2.ve 3.Kısım)",
        "Parti No": 4,
        "Parti Son Teslim Tarihi": "2025-05-15",
        "Parti Tutarı": 5997000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/556677",
        "Yüklenici Firma": "Kapak Döküm Sanayi Anonim Şirketi",
        "İhale Adı": "Dökme Demir Muayene Bacası Temini",
        "Parti No": 1,
        "Parti Son Teslim Tarihi": "2025-05-15",
        "Parti Tutarı": 2270625,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2024/998877",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Stop Vana, Sayaç Rakoru, Nipel ve Nipel Redüksiyon Temini İşi (1. Kısım)",
        "Parti No": 4,
        "Parti Son Teslim Tarihi": "2025-05-16",
        "Parti Tutarı": 4068750,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2024/123",
        "Yüklenici Firma": "ABC Döküm San. ve Tic. Ltd. Şti.",
        "İhale Adı": "Stop Vana, Sayac Rakoru, Nipel ve Nipel Redüksiyon Temini İşi (4. 5. ve 6.Kısım)",
        "Parti No": 4,
        "Parti Son Teslim Tarihi": "2025-05-19",
        "Parti Tutarı": 813750,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2024/1000",
        "Yüklenici Firma": "Hidrolik Pres Döküm Sanayi A.Ş",
        "İhale Adı": "Stop Vana, Sayac Rakoru, Nipel ve Nipel Redüksiyon Temini İşi (2.ve 3.Kısım)",
        "Parti No": 5,
        "Parti Son Teslim Tarihi": "2025-06-14",
        "Parti Tutarı": 8097000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/23456",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "50.000 Adet DN20mm R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 1,
        "Parti Son Teslim Tarihi": "2025-06-14",
        "Parti Tutarı": 2192000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/556677",
        "Yüklenici Firma": "Kapak Döküm Sanayi Anonim Şirketi",
        "İhale Adı": "Dökme Demir Muayene Bacası Temini",
        "Parti No": 2,
        "Parti Son Teslim Tarihi": "2025-06-14",
        "Parti Tutarı": 2270625,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2024/998877",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Stop Vana, Sayaç Rakoru, Nipel ve Nipel Redüksiyon Temini İşi (1. Kısım)",
        "Parti No": 5,
        "Parti Son Teslim Tarihi": "2025-06-15",
        "Parti Tutarı": 4068750,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2024/123",
        "Yüklenici Firma": "ABC Döküm San. ve Tic. Ltd. Şti.",
        "İhale Adı": "Stop Vana, Sayac Rakoru, Nipel ve Nipel Redüksiyon Temini İşi (4. 5. ve 6.Kısım)",
        "Parti No": 5,
        "Parti Son Teslim Tarihi": "2025-06-18",
        "Parti Tutarı": 813750,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2024/1000",
        "Yüklenici Firma": "Hidrolik Pres Döküm Sanayi A.Ş",
        "İhale Adı": "Stop Vana, Sayac Rakoru, Nipel ve Nipel Redüksiyon Temini İşi (2.ve 3.Kısım)",
        "Parti No": 6,
        "Parti Son Teslim Tarihi": "2025-07-14",
        "Parti Tutarı": 2100000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/23456",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "50.000 Adet DN20mm R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 2,
        "Parti Son Teslim Tarihi": "2025-07-14",
        "Parti Tutarı": 2192000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/556677",
        "Yüklenici Firma": "Kapak Döküm Sanayi Anonim Şirketi",
        "İhale Adı": "Dökme Demir Muayene Bacası Temini",
        "Parti No": 3,
        "Parti Son Teslim Tarihi": "2025-07-14",
        "Parti Tutarı": 2270625,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2024/998877",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Stop Vana, Sayaç Rakoru, Nipel ve Nipel Redüksiyon Temini İşi (1. Kısım)",
        "Parti No": 6,
        "Parti Son Teslim Tarihi": "2025-07-15",
        "Parti Tutarı": 5425000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/65656500",
        "Yüklenici Firma": "Hidrant Sanayi Ticaret Limited Şirketi",
        "İhale Adı": "Yangın Musluğu Temini İşi",
        "Parti No": 1,
        "Parti Son Teslim Tarihi": "2025-07-19",
        "Parti Tutarı": 2215000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/23456",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "50.000 Adet DN20mm R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 3,
        "Parti Son Teslim Tarihi": "2025-08-13",
        "Parti Tutarı": 2192000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/556677",
        "Yüklenici Firma": "Kapak Döküm Sanayi Anonim Şirketi",
        "İhale Adı": "Dökme Demir Muayene Bacası Temini",
        "Parti No": 4,
        "Parti Son Teslim Tarihi": "2025-08-13",
        "Parti Tutarı": 2270625,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2024/998877",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Stop Vana, Sayaç Rakoru, Nipel ve Nipel Redüksiyon Temini İşi (1. Kısım)",
        "Parti No": 7,
        "Parti Son Teslim Tarihi": "2025-08-14",
        "Parti Tutarı": 5425000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/5500066",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Pirinç Kör Tapa Temini İşi",
        "Parti No": 1,
        "Parti Son Teslim Tarihi": "2025-08-15",
        "Parti Tutarı": 756250,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/65656500",
        "Yüklenici Firma": "Hidrant Sanayi Ticaret Limited Şirketi",
        "İhale Adı": "Yangın Musluğu Temini İşi",
        "Parti No": 2,
        "Parti Son Teslim Tarihi": "2025-08-18",
        "Parti Tutarı": 2215000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/23456",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "50.000 Adet DN20mm R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 4,
        "Parti Son Teslim Tarihi": "2025-09-12",
        "Parti Tutarı": 2192000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/556677",
        "Yüklenici Firma": "Kapak Döküm Sanayi Anonim Şirketi",
        "İhale Adı": "Dökme Demir Muayene Bacası Temini",
        "Parti No": 5,
        "Parti Son Teslim Tarihi": "2025-09-12",
        "Parti Tutarı": 2270625,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2024/998877",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Stop Vana, Sayaç Rakoru, Nipel ve Nipel Redüksiyon Temini İşi (1. Kısım)",
        "Parti No": 8,
        "Parti Son Teslim Tarihi": "2025-09-13",
        "Parti Tutarı": 5425000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/5500066",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Pirinç Kör Tapa Temini İşi",
        "Parti No": 2,
        "Parti Son Teslim Tarihi": "2025-09-14",
        "Parti Tutarı": 418750,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/65656500",
        "Yüklenici Firma": "Hidrant Sanayi Ticaret Limited Şirketi",
        "İhale Adı": "Yangın Musluğu Temini İşi",
        "Parti No": 3,
        "Parti Son Teslim Tarihi": "2025-09-17",
        "Parti Tutarı": 2215000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/999888",
        "Yüklenici Firma": "Plastik San. Ltd. Şti.",
        "İhale Adı": "Polietilen Boru (PE100) Temini 1.Kısım (∅ 32)",
        "Parti No": 1,
        "Parti Son Teslim Tarihi": "2025-10-04",
        "Parti Tutarı": 407250,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/23456",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "50.000 Adet DN20mm R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 5,
        "Parti Son Teslim Tarihi": "2025-10-12",
        "Parti Tutarı": 2192000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/556677",
        "Yüklenici Firma": "Kapak Döküm Sanayi Anonim Şirketi",
        "İhale Adı": "Dökme Demir Muayene Bacası Temini",
        "Parti No": 6,
        "Parti Son Teslim Tarihi": "2025-10-12",
        "Parti Tutarı": 2270625,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/5500066",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Pirinç Kör Tapa Temini İşi",
        "Parti No": 3,
        "Parti Son Teslim Tarihi": "2025-10-14",
        "Parti Tutarı": 418750,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/65656500",
        "Yüklenici Firma": "Hidrant Sanayi Ticaret Limited Şirketi",
        "İhale Adı": "Yangın Musluğu Temini İşi",
        "Parti No": 4,
        "Parti Son Teslim Tarihi": "2025-10-17",
        "Parti Tutarı": 2215000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/11223344",
        "Yüklenici Firma": "Sfero Döküm Ticaret Limited Şirketi",
        "İhale Adı": "Kolay Tamir Parçası Temini",
        "Parti No": 1,
        "Parti Son Teslim Tarihi": "2025-10-26",
        "Parti Tutarı": 525000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/999888",
        "Yüklenici Firma": "Plastik San. Ltd. Şti.",
        "İhale Adı": "Polietilen Boru (PE100) Temini 1.Kısım (∅ 32)",
        "Parti No": 2,
        "Parti Son Teslim Tarihi": "2025-11-03",
        "Parti Tutarı": 407250,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/23456",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "50.000 Adet DN20mm R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 6,
        "Parti Son Teslim Tarihi": "2025-11-11",
        "Parti Tutarı": 2192000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/556677",
        "Yüklenici Firma": "Kapak Döküm Sanayi Anonim Şirketi",
        "İhale Adı": "Dökme Demir Muayene Bacası Temini",
        "Parti No": 7,
        "Parti Son Teslim Tarihi": "2025-11-11",
        "Parti Tutarı": 2270625,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/886600",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Pirinç Bağlantı Parçası 3/4 Temini",
        "Parti No": 1,
        "Parti Son Teslim Tarihi": "2025-11-12",
        "Parti Tutarı": 774375,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/5500066",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Pirinç Kör Tapa Temini İşi",
        "Parti No": 4,
        "Parti Son Teslim Tarihi": "2025-11-13",
        "Parti Tutarı": 418750,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/65656500",
        "Yüklenici Firma": "Hidrant Sanayi Ticaret Limited Şirketi",
        "İhale Adı": "Yangın Musluğu Temini İşi",
        "Parti No": 5,
        "Parti Son Teslim Tarihi": "2025-11-16",
        "Parti Tutarı": 2215000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/11223344",
        "Yüklenici Firma": "Sfero Döküm Ticaret Limited Şirketi",
        "İhale Adı": "Kolay Tamir Parçası Temini",
        "Parti No": 2,
        "Parti Son Teslim Tarihi": "2025-11-25",
        "Parti Tutarı": 525000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/1111111",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "45.000 Adet DN20 mm Hız Esaslı R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 1,
        "Parti Son Teslim Tarihi": "2025-11-26",
        "Parti Tutarı": 616000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/999888",
        "Yüklenici Firma": "Boru Malzemeleri Ltd. Şti.",
        "İhale Adı": "Polietilen Boru (PE100) Temini 2.Kısım (∅ 40)",
        "Parti No": 3,
        "Parti Son Teslim Tarihi": "2025-12-03",
        "Parti Tutarı": 633750,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/23456",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "50.000 Adet DN20mm R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 7,
        "Parti Son Teslim Tarihi": "2025-12-11",
        "Parti Tutarı": 2192000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/556677",
        "Yüklenici Firma": "Kapak Döküm Sanayi Anonim Şirketi",
        "İhale Adı": "Dökme Demir Muayene Bacası Temini",
        "Parti No": 8,
        "Parti Son Teslim Tarihi": "2025-12-11",
        "Parti Tutarı": 2270625,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/886600",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Pirinç Bağlantı Parçası 3/4 Temini",
        "Parti No": 2,
        "Parti Son Teslim Tarihi": "2025-12-12",
        "Parti Tutarı": 774375,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/5500066",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Pirinç Kör Tapa Temini İşi",
        "Parti No": 5,
        "Parti Son Teslim Tarihi": "2025-12-13",
        "Parti Tutarı": 206250,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/11223344",
        "Yüklenici Firma": "Sfero Döküm Ticaret Limited Şirketi",
        "İhale Adı": "Kolay Tamir Parçası Temini",
        "Parti No": 3,
        "Parti Son Teslim Tarihi": "2025-12-25",
        "Parti Tutarı": 632500,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/1111111",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "45.000 Adet DN20 mm Hız Esaslı R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 2,
        "Parti Son Teslim Tarihi": "2025-12-26",
        "Parti Tutarı": 616000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/999888",
        "Yüklenici Firma": "Plastik San. Ltd. Şti.",
        "İhale Adı": "Polietilen Boru (PE100) Temini 1.Kısım (∅ 32)",
        "Parti No": 4,
        "Parti Son Teslim Tarihi": "2026-01-02",
        "Parti Tutarı": 407250,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "1",
        "Kabul İşlemi": "1",
        "Açıklama": "Evrak müdürde imza bekliyor."
    },
    {
        "İKN": "2025/23456",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "50.000 Adet DN20mm R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 8,
        "Parti Son Teslim Tarihi": "2026-01-10",
        "Parti Tutarı": 2192000,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "0",
        "Kabul İşlemi": "0",
        "Açıklama": "Test Sonuçları inceleniyor...."
    },
    {
        "İKN": "2025/556677",
        "Yüklenici Firma": "Kapak Döküm Sanayi Anonim Şirketi",
        "İhale Adı": "Dökme Demir Muayene Bacası Temini",
        "Parti No": 9,
        "Parti Son Teslim Tarihi": "2026-01-10",
        "Parti Tutarı": 2270625,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "0",
        "Test sonuçları geldi": "0",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "0",
        "Kabul İşlemi": "0",
        "Açıklama": "Ambalajlama Sıkıntılı"
    },
    {
        "İKN": "2025/886600",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Pirinç Bağlantı Parçası 3/4 Temini",
        "Parti No": 3,
        "Parti Son Teslim Tarihi": "2026-01-11",
        "Parti Tutarı": 774375,
        "Ambar teslimi gerçekleşti": "1",
        "Testler başladı": "1",
        "Test sonuçları geldi": "1",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "0",
        "Kabul İşlemi": "0",
        "Açıklama": "Sonuçlar uygun değilParti reddedilebilir"
    },
    {
        "İKN": "2025/5500066",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Pirinç Kör Tapa Temini İşi",
        "Parti No": 6,
        "Parti Son Teslim Tarihi": "2026-01-12",
        "Parti Tutarı": 206250,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/11223344",
        "Yüklenici Firma": "Sfero Döküm Ticaret Limited Şirketi",
        "İhale Adı": "Kolay Tamir Parçası Temini",
        "Parti No": 4,
        "Parti Son Teslim Tarihi": "2026-01-24",
        "Parti Tutarı": 780000,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/1111111",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "45.000 Adet DN20 mm Hız Esaslı R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 3,
        "Parti Son Teslim Tarihi": "2026-01-25",
        "Parti Tutarı": 2156000,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/999888",
        "Yüklenici Firma": "Plastik San. Ltd. Şti.",
        "İhale Adı": "Polietilen Boru (PE100) Temini 1.Kısım (∅ 32)",
        "Parti No": 5,
        "Parti Son Teslim Tarihi": "2026-02-01",
        "Parti Tutarı": 407250,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/23456",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "50.000 Adet DN20mm R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 9,
        "Parti Son Teslim Tarihi": "2026-02-09",
        "Parti Tutarı": 2192000,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/556677",
        "Yüklenici Firma": "Kapak Döküm Sanayi Anonim Şirketi",
        "İhale Adı": "Dökme Demir Muayene Bacası Temini",
        "Parti No": 10,
        "Parti Son Teslim Tarihi": "2026-02-09",
        "Parti Tutarı": 2270625,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/886600",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Pirinç Bağlantı Parçası 3/4 Temini",
        "Parti No": 4,
        "Parti Son Teslim Tarihi": "2026-02-10",
        "Parti Tutarı": 2323125,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/5500066",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Pirinç Kör Tapa Temini İşi",
        "Parti No": 7,
        "Parti Son Teslim Tarihi": "2026-02-11",
        "Parti Tutarı": 206250,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/11223344",
        "Yüklenici Firma": "Sfero Döküm Ticaret Limited Şirketi",
        "İhale Adı": "Kolay Tamir Parçası Temini",
        "Parti No": 5,
        "Parti Son Teslim Tarihi": "2026-02-23",
        "Parti Tutarı": 375000,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/1111111",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "45.000 Adet DN20 mm Hız Esaslı R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 4,
        "Parti Son Teslim Tarihi": "2026-02-24",
        "Parti Tutarı": 2156000,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/999888",
        "Yüklenici Firma": "Plastik San. Ltd. Şti.",
        "İhale Adı": "Polietilen Boru (PE100) Temini 1.Kısım (∅ 32)",
        "Parti No": 6,
        "Parti Son Teslim Tarihi": "2026-03-03",
        "Parti Tutarı": 407250,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/23456",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "50.000 Adet DN20mm R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 10,
        "Parti Son Teslim Tarihi": "2026-03-11",
        "Parti Tutarı": 2192000,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/886600",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Pirinç Bağlantı Parçası 3/4 Temini",
        "Parti No": 5,
        "Parti Son Teslim Tarihi": "2026-03-12",
        "Parti Tutarı": 2323125,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/5500066",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Pirinç Kör Tapa Temini İşi",
        "Parti No": 8,
        "Parti Son Teslim Tarihi": "2026-03-13",
        "Parti Tutarı": 206250,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/1111111",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "45.000 Adet DN20 mm Hız Esaslı R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 5,
        "Parti Son Teslim Tarihi": "2026-03-26",
        "Parti Tutarı": 2156000,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/999888",
        "Yüklenici Firma": "Plastik San. Ltd. Şti.",
        "İhale Adı": "Polietilen Boru (PE100) Temini 1.Kısım (∅ 32)",
        "Parti No": 7,
        "Parti Son Teslim Tarihi": "2026-04-02",
        "Parti Tutarı": 407250,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/23456",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "50.000 Adet DN20mm R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 11,
        "Parti Son Teslim Tarihi": "2026-04-10",
        "Parti Tutarı": 2740000,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/886600",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Pirinç Bağlantı Parçası 3/4 Temini",
        "Parti No": 6,
        "Parti Son Teslim Tarihi": "2026-04-11",
        "Parti Tutarı": 2323125,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/1111111",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "45.000 Adet DN20 mm Hız Esaslı R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 6,
        "Parti Son Teslim Tarihi": "2026-04-25",
        "Parti Tutarı": 2156000,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/23456",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "50.000 Adet DN20mm R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 12,
        "Parti Son Teslim Tarihi": "2026-05-10",
        "Parti Tutarı": 2740000,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/886600",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Pirinç Bağlantı Parçası 3/4 Temini",
        "Parti No": 7,
        "Parti Son Teslim Tarihi": "2026-05-11",
        "Parti Tutarı": 3097500,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/1111111",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "45.000 Adet DN20 mm Hız Esaslı R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 7,
        "Parti Son Teslim Tarihi": "2026-05-25",
        "Parti Tutarı": 2464000,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/886600",
        "Yüklenici Firma": "Demir Metal Sanayi Limited Şirketi",
        "İhale Adı": "Pirinç Bağlantı Parçası 3/4 Temini",
        "Parti No": 8,
        "Parti Son Teslim Tarihi": "2026-06-10",
        "Parti Tutarı": 3097500,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/1111111",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "45.000 Adet DN20 mm Hız Esaslı R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 8,
        "Parti Son Teslim Tarihi": "2026-06-24",
        "Parti Tutarı": 3080000,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/1111111",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "45.000 Adet DN20 mm Hız Esaslı R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 9,
        "Parti Son Teslim Tarihi": "2026-07-24",
        "Parti Tutarı": 3080000,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/1111111",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "45.000 Adet DN20 mm Hız Esaslı R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 10,
        "Parti Son Teslim Tarihi": "2026-08-23",
        "Parti Tutarı": 3080000,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/1111111",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "45.000 Adet DN20 mm Hız Esaslı R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 11,
        "Parti Son Teslim Tarihi": "2026-09-22",
        "Parti Tutarı": 3080000,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2025/1111111",
        "Yüklenici Firma": "Ölçüm Sanayi ve Ticaret Anonim Şirketi",
        "İhale Adı": "45.000 Adet DN20 mm Hız Esaslı R100 Soğuk Su Sayacı Temini İşi",
        "Parti No": 12,
        "Parti Son Teslim Tarihi": "2026-10-22",
        "Parti Tutarı": 3080000,
        "Ambar teslimi gerçekleşti": "null",
        "Testler başladı": "null",
        "Test sonuçları geldi": "null",
        "Muayene Ve Kabul Heyet Raporu imza aşamasında": "null",
        "Kabul İşlemi": "0",
        "Açıklama": "null"
    },
    {
        "İKN": "2026/999888",
        "Yüklenici Firma": "ERBİL Elektronik",
        "İhale Adı": "Elektronik Komponent Alımı",
        "Parti No": 1,
        "Parti Son Teslim Tarihi": "2026-01-26",
        "Parti Tutarı": 2500000
    },
    {
        "İKN": "2026/999888",
        "Yüklenici Firma": "ERBİL Elektronik",
        "İhale Adı": "Elektronik Komponent Alımı",
        "Parti No": 2,
        "Parti Son Teslim Tarihi": "2026-02-25",
        "Parti Tutarı": 2500000
    },
    {
        "İKN": "2026/999888",
        "Yüklenici Firma": "ERBİL Elektronik",
        "İhale Adı": "Elektronik Komponent Alımı",
        "Parti No": 3,
        "Parti Son Teslim Tarihi": "2026-03-27",
        "Parti Tutarı": 2500000
    },
    {
        "İKN": "2026/999888",
        "Yüklenici Firma": "ERBİL Elektronik",
        "İhale Adı": "Elektronik Komponent Alımı",
        "Parti No": 4,
        "Parti Son Teslim Tarihi": "2026-04-26",
        "Parti Tutarı": 2500000
    },
    {
        "İKN": "2026/999888",
        "Yüklenici Firma": "ERBİL Elektronik",
        "İhale Adı": "Elektronik Komponent Alımı",
        "Parti No": 5,
        "Parti Son Teslim Tarihi": "2026-05-26",
        "Parti Tutarı": 2500000
    },
    {
        "İKN": "2026/999888",
        "Yüklenici Firma": "ERBİL Elektronik",
        "İhale Adı": "Elektronik Komponent Alımı",
        "Parti No": 6,
        "Parti Son Teslim Tarihi": "2026-06-25",
        "Parti Tutarı": 2500000
    },
    {
        "İKN": "2026/999888",
        "Yüklenici Firma": "ERBİL Elektronik",
        "İhale Adı": "Elektronik Komponent Alımı",
        "Parti No": 7,
        "Parti Son Teslim Tarihi": "2026-07-25",
        "Parti Tutarı": 2500000
    },
    {
        "İKN": "2026/999888",
        "Yüklenici Firma": "ERBİL Elektronik",
        "İhale Adı": "Elektronik Komponent Alımı",
        "Parti No": 8,
        "Parti Son Teslim Tarihi": "2026-08-24",
        "Parti Tutarı": 2500000
    }
];